language: go
sudo: false

matrix:
  include:
    - go: "1.9"
    - go: "1.10"
      env: VET=1
    # FYI: we don't vet with 1.11 because it complains about usage
    # of a deprecated API in go/types. However, we can't move to
    # newer non-deprecated API and still support 1.9 and 1.10.
    - go: "1.11"
    - go: tip

script:
  - if [[ "$VET" = 1 ]]; then make; else make deps test; fi
